apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-analysis
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 30s
    successCondition: result < 0.07
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1727-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project-todo-app-namespace"}[10m]))) 