apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-todo-app-storage
  namespace: project-todo-app-namespace
spec:
  storageClassName: project-todo-app-storage
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/project-todo-app
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0