apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-todo-app
  namespace: project-todo-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-todo-app
  strategy:
    canary:
      steps:
      - setWeight: 100
      - analysis:
          templates:
          - templateName: cpu-usage-analysis
      - pause:
          duration: 30s
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project-todo-app
    spec:
      volumes:
        - name: project-todo-app-storage
          persistentVolumeClaim:
            claimName: project-todo-app-storage
      containers:
        - name: project-todo-app-frontend
          image: hzville/devops-with-kubernetes:project-todo-app
          imagePullPolicy: Always
          volumeMounts:
          - name: project-todo-app-storage
            mountPath: /usr/src/app/files
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
        - name: project-todo-app-backend
          image: hzville/devops-with-kubernetes:project-todo-app-backend
          imagePullPolicy: Always
          volumeMounts:
          - name: project-todo-app-storage
            mountPath: /usr/src/app/files
          env:
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "user1"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key:  POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: "new_db"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 10