apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wEv3cVW26eYap35r,iv:TJPDXcs7cUj8HgGfW7nqbVRqeygR1C1CmnT8kUcph3U=,tag:fo4T6VoFpoRqmWE3dPBzMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qg02pc7argqyms48aa7xp5rucnye7fry94lxxqxwgz7fds340uls86u9xz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBValJpNFBxVUxLVUUzWUNJ
            dG1OaWNZR0g4bFFwSHVQdVoxVjVqNnpqRkdJCnlFMGh3bkU1OWFTbC9PY2dEWmVq
            ZisrNFZQL2xhN0x4aTIzaWFGbUMybjQKLS0tIHFZa0pBS3JRcHNVV0tWR05tNVNv
            SzR0VjJ5WVJuZys1K1duVEJRaW01cjQKolEoNHWE9I+LnVpt7eua2xo6H1MjGb+w
            rwvJrDDQuliaOVlczilvuspYjijVqB1+0LKPW0nGLtaXz5I0ny1UMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T22:06:08Z"
    mac: ENC[AES256_GCM,data:kK5LsAEoJ6Ctz1lycdeeRpCkbWblQvcnS4nFxJZsXascDP0ivYc/AtiHbaOM9GXPdHEgZ+oLogSPRpVikO73Vlc1D5s7oMaRO2nYPzzGnyETvl6ZGNqQnTqjHErfbZ/gd/zrT3lta25Ht7K9gepaU8OATYzzk/B6GXKgSFsNQ6o=,iv:XTuS3ltvwbv4KP4AcRsLsMpmx86BKw/Q06ac9Eq54zg=,tag:9/dhGqhEcLE7i+87rt3igQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
