apiVersion: v1
kind: Service
metadata:
  name: project-todo-app
spec:
  type: NodePort
  selector:
    app: project-todo-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1111
      targetPort: 3001