apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: hzville/devops-with-kubernetes:ping-pong-app
          imagePullPolicy: Always