apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app
  namespace: log-output-app-namespace
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 4444
      protocol: TCP
      targetPort: 3002